import type { Metadata } from "next";
import "./globals.scss";

require("@solana/wallet-adapter-react-ui/styles.css");

import { ContextProvider } from "@/contexts/ContextProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
